### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by YaFanYen** [facebookresearch/svoice#32]
Hi,
I'm trying to train on the AVSpeech dataset but have encountered the following error:

    (virtualenv) (base) ed716@ed716:~/Documents/NewSSD/gated_DPRNN$ sudo python3 train.py                                   
    [2021-06-14 20:23:48,612][__main__][INFO] - For logs, checkpoints and samples check /media/ed716/NewSSD/gated_DPRNN/out$
    uts/exp_                                                                                                                
    [2021-06-14 20:23:48,612][__main__][DEBUG] - {'sample_rate': 8000, 'segment': 2, 'stride': 1, 'pad': True, 'cv_maxlen': 
    8, 'validfull': 1, 'num_prints': 5, 'device': 'cuda', 'num_workers': 5, 'verbose': 1, 'show': 0, 'checkpoint': True, 'c$
    ntinue_from': '', 'continue_best': False, 'restart': False, 'checkpoint_file': 'checkpoint.th', 'history_file': 'histor$
    .json', 'samples_dir': 'samples', 'seed': 2036, 'dummy': None, 'pesq': False, 'eval_every': 10, 'keep_last': 0, 'optim'$
     'adam', 'lr': 0.0005, 'beta2': 0.999, 'stft_loss': False, 'stft_sc_factor': 0.5, 'stft_mag_factor': 0.5, 'epochs': 100$
     'batch_size': 1, 'max_norm': 5, 'lr_sched': 'step', 'step': {'step_size': 2, 'gamma': 0.98}, 'plateau': {'factor': 0.5$
     'patience': 5}, 'model': 'swave', 'swave': {'N': 128, 'L': 8, 'H': 128, 'R': 6, 'C': 2, 'input_normalize': False}, 'dd$
    ': False, 'ddp_backend': 'nccl', 'rendezvous_file': './rendezvous', 'rank': None, 'world_size': None, 'dset': {'train': 
    '/media/ed716/NewSSD/gated_DPRNN/egs/debug/tr', 'valid': '/media/ed716/NewSSD/gated_DPRNN/egs/debug/cv', 'test': '/medi$
    /ed716/NewSSD/gated_DPRNN/egs/debug/tt', 'mix_json': '/media/ed716/NewSSD/gated_DPRNN/egs/debug/tr/mix.json', 'mix_dir'$
     None}}                                                                                                                 
    /home/ed716/virtualenv/lib/python3.6/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being $
    eprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. 
    Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.         
      '"sox" backend is being deprecated. '                                                                                 
    [2021-06-14 20:23:49,509][__main__][INFO] - Running on host ed716                                                       
    [2021-06-14 20:23:51,179][svoice.solver][INFO] - ---------------------------------------------------------------------- 
    [2021-06-14 20:23:51,179][svoice.solver][INFO] - Training...                                                            
    [2021-06-14 20:24:05,661][svoice.solver][INFO] - Train | Epoch 1 | 40/200 | 2.8 it/sec | Loss 25.22286
    [2021-06-14 20:24:20,099][svoice.solver][INFO] - Train | Epoch 1 | 80/200 | 2.8 it/sec | Loss 23.01586
    [2021-06-14 20:24:34,336][svoice.solver][INFO] - Train | Epoch 1 | 120/200 | 2.8 it/sec | Loss 22.67385
    [2021-06-14 20:24:48,426][svoice.solver][INFO] - Train | Epoch 1 | 160/200 | 2.8 it/sec | Loss 22.08590
    [2021-06-14 20:25:02,552][svoice.solver][INFO] - Train | Epoch 1 | 200/200 | 2.8 it/sec | Loss 21.87745
    [2021-06-14 20:25:02,553][svoice.solver][INFO] - Train Summary | End of Epoch 1 | Time 71.37s | Train Loss 21.87745
    [2021-06-14 20:25:02,553][svoice.solver][INFO] - ----------------------------------------------------------------------
    [2021-06-14 20:25:02,553][svoice.solver][INFO] - Cross validation...
    [2021-06-14 20:25:02,775][__main__][ERROR] - Some error happened
    Traceback (most recent call last):
      File "train.py", line 119, in main
        _main(args)
      File "train.py", line 113, in _main
        run(args)
      File "train.py", line 94, in run
        solver.train()
      File "/media/ed716/NewSSD/gated_DPRNN/svoice/solver.py", line 131, in train
        valid_loss = self._run_one_epoch(epoch, cross_valid=True)
      File "/media/ed716/NewSSD/gated_DPRNN/svoice/solver.py", line 210, in _run_one_epoch
        sources, est_src, lengths)
      File "/media/ed716/NewSSD/gated_DPRNN/svoice/models/sisnr_loss.py", line 23, in cal_loss
        source_lengths)
      File "/media/ed716/NewSSD/gated_DPRNN/svoice/models/sisnr_loss.py", line 39, in cal_si_snr_with_pit
        assert source.size() == estimate_source.size()
    AssertionError

The only variable I've changed was segment=2, batchsize=1,
I've also tried with segment=1 and 3 and 4, batchsize=2 and 4 but still getting the same error.

**Comment by umerjamil16** [comment]
Hello @YaFanYen , were you able to address this error? I am also facing the same error when training model of 3 speakers (link to my issue: https://github.com/facebookresearch/svoice/issues/54)
