### ISSUE TITLE
google colab problem appear ModuleNotFoundError: No module named 'svoice'

### ISSUE THREAD

**Issue by by-XG** [facebookresearch/svoice#38]
google colab

input is {!python /content/drive/MyDrive/test_2/svoice-master/svoice/separate.py /content/drive/MyDrive/test_2/svoice-master/outputs/exp_/checkpoint.th /content/drive/MyDrive/test_2/svoice-master/out_data_1 --mix_dir=/content/drive/MyDrive/test_2/svoice-master/op11 }

output is {Traceback (most recent call last):
  File "/content/drive/MyDrive/test_2/svoice-master/svoice/separate.py", line 133, in <module>
    separate(args, local_out_dir=args.out_dir)
  File "/content/drive/MyDrive/test_2/svoice-master/svoice/separate.py", line 88, in separate
    pkg = torch.load(args.model_path)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'svoice'}

Why would it return ModuleNotFoundError: No module named 'svoice

**Comment by adiyoss** [comment]
Hi @by-XG,
Try the following command: `python -m svoice.separate <path to the model checkpoint> <path to store the files> --mix_dir=<path to the mixture to be separated>`
In case you want to separation on a cpu, you should also add `--device=cpu` to the command
