### ISSUE TITLE
raise TypeError(msg) TypeError: 'required' is an invalid argument for positionals

### ISSUE THREAD

**Issue by jayita13** [facebookresearch/svoice#5]
I'm facing problem in while running the train.py file 
```
[2020-12-28 16:29:58,757][__main__][INFO] - For logs, checkpoints and samples check /content/svoice/outputs/exp_
[2020-12-28 16:30:01,919][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "train.py", line 118, in main
    _main(args)
  File "train.py", line 112, in _main
    run(args)
  File "train.py", line 30, in run
    from svoice.solver import Solver
  File "/content/svoice/svoice/solver.py", line 21, in <module>
    from .separate import separate
  File "/content/svoice/svoice/separate.py", line 27, in <module>
    parser.add_argument("model_path", type=str, required=True, help="Model name")
  File "/usr/lib/python3.6/argparse.py", line 1329, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
  File "/usr/lib/python3.6/argparse.py", line 1441, in _get_positional_kwargs
    raise TypeError(msg)
TypeError: 'required' is an invalid argument for positional

```
How can I solve it?

**Comment by adiyoss** [comment]
Hi @jayita13,
Sorry about that, I fixed it, it should be fine now. 
Can you try to pull and retry to train?

**Comment by jayita13** [comment]
Hi @adiyoss 
Thank you for resolving the issue
It's working
Training is happening now
