### ISSUE TITLE
Execute make_dataset err（ValueError: low >= high）

### ISSUE THREAD

**Issue by srdfjy** [facebookresearch/svoice#73]
Hi，when I run make_dataset.py, the following error occurs.

data
---
ls ../dataset/2spk/tr | head -n 2
20170001P00001A0024.wav
20170001P00001I0112.wav

config
---
in_path=../dataset/2spk/tr
out_path=../dataset/2spk_mix/tr
noise_path=
num_of_speakers=2
num_of_scenes=80
sec=4
sr=16000

python scripts/make_dataset.py \
    --in_path=$in_path \
    --out_path=$out_path \
    --num_of_speakers=$num_of_speakers \
    --num_of_scenes=$num_of_scenes \
    --sec=$sec \
    --sr=$sr

err
---
Traceback (most recent call last):
  File "scripts/make_dataset.py", line 238, in <module>
    main(args)
  File "scripts/make_dataset.py", line 223, in main
    Data.gen_scene(args.num_of_speakers, i, args.out_path)
  File "scripts/make_dataset.py", line 162, in gen_scene
    S, sig_idx = self.fetch_signals(scenario_num_of_speakers)
  File "scripts/make_dataset.py", line 58, in fetch_signals
    select_name_indx = np.random.randint(
  File "mtrand.pyx", line 746, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1254, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high

**Comment by mattnappo** [comment]
What was the solution? I am also getting this @srdfjy

**Comment by srdfjy** [comment]
![image](https://user-images.githubusercontent.com/66103286/172326768-efa5390b-5070-42f4-afc5-6bb2b32a53ec.png)
