### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by skwolvie** [facebookresearch/svoice#8]
```
python -m svoice.data.audio $spk1 > $out/s1.json
Traceback (most recent call last):
  File "/home/sachin/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sachin/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sachin/svoice/svoice/data/audio.py", line 87, in <module>
    json.dump(find_audio_files(sys.argv[1]), sys.stdout, indent=4)
IndexError: list index out of range
```

**Comment by skwolvie** [comment]
I got this above error. Can someone pls help with a solution to this error?

I followed the steps in readme, installed all packages, and ran the sample code. I'm not sure why I am getting this error.

**Comment by skwolvie** [comment]
Just re-ran pip3 install requirements.txt and it worked.
