### ISSUE TITLE
WHere is the trained model saved after training? How to pass a differnt path to save model through CLI?

### ISSUE THREAD

**Issue by skwolvie** [facebookresearch/svoice#9]
Hi, 

I followed the readme steps and I had no issues with training the model. 
I want to evaluate the trained model but I'm not able to locate the path_to_model_dir to pass the saved model for evaluation.

List of commands I ran after clean setup:
```
./make_debug.sh
python train.py
python train.py lr=0.001
python train.py ddp=1
```

I had some issue with running the command below:
```
python train.py dset=librimix lr=0.001 swave.R=8
```
```
Error:
$ python train.py dset=librimix lr=0.001 swave.R=8
Traceback (most recent call last):
  File "train.py", line 126, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/hydra.py", line 100, in run
    cfg = self.compose_config(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/config_loader_impl.py", line 256, in _load_configuration
    cfg = self._merge_defaults_into_config(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/config_loader_impl.py", line 805, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, user_list)
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/config_loader_impl.py", line 777, in merge_defaults_list_into_config
    merged_cfg = self._merge_config(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/config_loader_impl.py", line 715, in _merge_config
    raise MissingConfigException(msg, new_cfg, options)
hydra.errors.MissingConfigException: Could not load dset/librimix.
Available options:
	debug
```

I want to evaluate the trained models and I tried to look in the PWD and I did not find the model saved there. 
```
python -m svoice.evaluate <**path to the model**> <path to folder containing mix.json and all target separated channels json files s<ID>.json>
````

What is the default path to the model?
How do I explicitly pass a path to model dir of my chosen dir?

**Comment by adiyoss** [comment]
Hi @skwolvie! 
So for the `train.py` command, it seems like need to create a json file for it (similar to the debug) inside the `egs/dset` folder. 
Regarding the saved model, the default should be under `outputs/` folder. You can change it inside the config file here: https://github.com/facebookresearch/svoice/blob/master/conf/config.yaml#L81

Generally, all the configurations are being maintained using Hydra package (https://hydra.cc/). I suggest getting familiar with this package, it will make things easier and clearer.
