### ISSUE TITLE
TypeError: cannot unpack non-iterable AudioMetaData object

### ISSUE THREAD

**Issue by Guneshwar24** [facebookresearch/svoice#94]
**Using dependencies:**
$ pip list
Package                Version
---------------------- ---------
antlr4-python3-runtime 4.8
audioread              3.0.1
certifi                2023.7.22
cffi                   1.16.0
charset-normalizer     3.3.0
colorama               0.4.6
colorlog               6.7.0
decorator              5.1.1
filelock               3.12.4
fsspec                 2023.9.2
hydra-colorlog         1.0.0
hydra-core             1.0.3
idna                   3.4
Jinja2                 3.1.2
joblib                 1.3.2
librosa                0.7.1
llvmlite               0.41.0
MarkupSafe             2.1.3
mpmath                 1.3.0
networkx               3.1
numba                  0.58.0
numpy                  1.25.2
omegaconf              2.1.2
pesq                   0.0.2
Pillow                 10.0.1
pip                    23.2.1
pycparser              2.21
pystoi                 0.3.3
PyYAML                 6.0.1
requests               2.31.0
resampy                0.4.2
scikit-learn           1.3.1
scipy                  1.11.3
setuptools             68.2.2
six                    1.16.0
soundfile              0.12.1
sympy                  1.12
threadpoolctl          3.2.0
torch                  2.1.0
torchaudio             2.1.0
torchvision            0.16.0
tqdm                   4.51.0
typing_extensions      4.8.0
urllib3                2.0.6

**ERROR:**

$ ./make_debug.sh
  0%|                                                     | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\auditivo.ai\svoice\svoice\data\audio.py", line 87, in <module>
    json.dump(find_audio_files(sys.argv[1]), sys.stdout, indent=4)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\auditivo.ai\svoice\svoice\data\audio.py", line 34, in find_audio_files       
    siginfo, _ = torchaudio.info(file)
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable AudioMetaData object
  0%|                                                     | 0/8 [00:00<?, ?it/s]        
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\auditivo.ai\svoice\svoice\data\audio.py", line 87, in <module>
    json.dump(find_audio_files(sys.argv[1]), sys.stdout, indent=4)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\auditivo.ai\svoice\svoice\data\audio.py", line 34, in find_audio_files       
    siginfo, _ = torchaudio.info(file)
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable AudioMetaData object
  0%|                                                     | 0/8 [00:00<?, ?it/s]        
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\auditivo.ai\svoice\svoice\data\audio.py", line 87, in <module>
    json.dump(find_audio_files(sys.argv[1]), sys.stdout, indent=4)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\auditivo.ai\svoice\svoice\data\audio.py", line 34, in find_audio_files       
    siginfo, _ = torchaudio.info(file)
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable AudioMetaData object
(auditivo)

**Comment by Feavore** [comment]
i'd got this issue. i removed '_' and modify line 34 & 35:
siginfo = torchaudio.info(file)
length = siginfo.num_frames // siginfo.sample_rate
